### ISSUE TITLE
issue: Type error when used with zod v4

### ISSUE THREAD

**Issue by shahinghasemi** [react-hook-form/resolvers#813]
### Version Number

5.2.1

### Steps to reproduce

```
import { z } from 'zod/v4';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';


const schema = z.object({ name: z.string() });

  const methods = useForm({
    resolver: zodResolver(schema),
  });

```
Here's I can't use the schema inside the zodResolver, typescript complains:

```
No overload matches this call.
  Overload 1 of 4, '(schema: Zod3Type<{ name: string; }, { name: string; }>, schemaOptions?: ParseParams | undefined, resolverOptions?: NonRawResolverOptions | undefined): Resolver<...>', gave the following error.
    Argument of type 'ZodObject<{ name: ZodString; }, $strip>' is not assignable to parameter of type 'Zod3Type<{ name: string; }, { name: string; }>'.
      Types of property '_def' are incompatible.
        Property 'typeName' is missing in type '$ZodObjectDef<{ name: ZodString; }>' but required in type '{ typeName: string; }'.
 Overload 2 of 4, '(schema: $ZodType<unknown, FieldValues, $ZodTypeInternals<unknown, FieldValues>>, schemaOptions?: ParseContext<$ZodIssue> | undefined, resolverOptions?: NonRawResolverOptions | undefined): Resolver<...>', gave the following error.
    Argument of type 'ZodObject<{ name: ZodString; }, $strip>' is not assignable to parameter of type '$ZodType<unknown, FieldValues, $ZodTypeInternals<unknown, FieldValues>>'.
      The types of '_zod.version.minor' are incompatible between these types.
        Type '1' is not assignable to type '0'.ts(2769)
```

Heres my package.json:

    "@hookform/resolvers": "^5.2.1",
    "react-hook-form": "^7.62.0",
    "typescript": "^5.9.2"

**Comment by EWisselink** [comment]
Try to downgrade to 5.2.0, if that works it is related to #803

**Comment by marcpicaud** [comment]
Had the same issue with 
```json
{
  "dependencies": {
    "@hookform/resolvers": "5.2.1",
    "react-hook-form": "7.62.0",
    "zod": "4.1.5"
  },
  "devDependencies": {
    "typescript": "5.8.3",
  }
}
```


--> Downgrading to 5.2.0 removed the issue.

**Comment by amomammadw** [comment]
updateing all packages, remove `node_modules` and `pnpm-lock.yaml` fixed my issue

**Comment by bennajah** [comment]
@panesar-ke 
> > updating all packages, remove `node_modules` and `pnpm-lock.yaml` fixed my issue
> 
> Worked for me as well.

Which versions

**Comment by marefati110** [comment]
The schema isn’t working properly when used with ZodType.

Tried updating all packages to the latest versions.
Removed node_modules and pnpm-lock.yaml, then reinstalled everything.
The issue still persists.

```ts

interface LoginPayload {
    username :string
    password: string
}

const loginSchema: ZodType<LoginPayload> = z.object({
	email: z.email("Enter a valid email address"),
	password: z
		.string()
		.min(6, "Password must be at least 8 characters")
		.max(32, "Password must be at most 32 characters"),
})
```

```ts
const { control, handleSubmit } = useForm({
	resolver: zodResolver(loginSchema),
})
```


```ts
No overload matches this call.
  Overload 1 of 4, '(schema: Zod3Type<LoginPayload, FieldValues>, schemaOptions?: ParseParams | undefined, resolverOptions?: NonRawResolverOptions | undefined): Resolver<...>', gave the following error.
    Argument of type 'ZodType<LoginPayload, unknown, $ZodTypeInternals<LoginPayload, unknown>>' is not assignable to parameter of type 'Zod3Type<LoginPayload, FieldValues>'.
      Types of property '_input' are incompatible.
        Type 'unknown' is not assignable to type 'FieldValues'.
  Overload 2 of 4, '(schema: $ZodType<unknown, FieldValues, $ZodTypeInternals<unknown, FieldValues>>, schemaOptions?: ParseContext<$ZodIssue> | undefined, resolverOptions?: NonRawResolverOptions | undefined): Resolver<...>', gave the following error.
    Argument of type 'ZodType<LoginPayload, unknown, $ZodTypeInternals<LoginPayload, unknown>>' is not assignable to parameter of type '$ZodType<unknown, FieldValues, $ZodTypeInternals<unknown, FieldValues>>'.
      Types of property '_zod' are incompatible.
        Type '$ZodTypeInternals<LoginPayload, unknown>' is not assignable to type '$ZodTypeInternals<unknown, FieldValues>'.
          Type 'unknown' is not assignable to type 'FieldValues'.ts(2769)
```

**Comment by hasahmad** [comment]
Issue was fixed.
I downgraded `@hookform/resolvers` to `^5.2.0` and removed `node_modules` and `pnpm-lock.yaml` and after `pnpm install` it's no longer giving me this error.

**Comment by Jisu-Woniu** [comment]
Is `@hookform/resolvers` depending on `zod@4.0.x`? Seems fixing `zod` to `~4.0.17` solved it. As the error message says:

```
      The types of '_zod.version.minor' are incompatible between these types.
        Type '1' is not assignable to type '0'.ts(2769)
```

This is wierd since minor version should not affect compatibility, so why is there such a type check?

**Comment by maxktz** [comment]
You can paste and use this v4 compatible resolver

```ts
import type { FieldValues, Resolver } from "react-hook-form";
import type * as z from "zod";

/**
 * Zod v4-compatible resolver for react-hook-form.
 * The `@hookform/resolvers/zod` package expects Zod v3 error shapes
 * and throws unhandled ZodErrors with Zod v4. This resolver uses
 * `safeParse` and maps v4 issues to react-hook-form `FieldErrors`.
 */
export function standardResolver<T extends FieldValues>(
  schema: z.ZodType<T>,
): Resolver<T> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- RHF Resolver type is overly strict
  return (async (values: any) => {
    const result = schema.safeParse(values);

    if (result.success) {
      return { values: result.data, errors: {} };
    }

    const fieldErrors: Record<string, { type: string; message: string }> = {};
    for (const issue of result.error.issues) {
      const path = issue.path.join(".");
      if (!fieldErrors[path]) {
        fieldErrors[path] = {
          type: issue.code,
          message: issue.message,
        };
      }
    }

    return { values: {} as T, errors: fieldErrors };
  }) as unknown as Resolver<T>;
}

```

**Comment by katsyuta** [comment]
The problem still exists; downgrading or updating packages does not fix it

The first issue report was published almost a year ago, and we still have no fix !?

**Comment by alexasomba** [comment]
> The problem still exists; downgrading or updating packages does not fix it
> 
> The first issue report was published almost a year ago, and we still have no fix !?
> 

You might want to consider Tanstack Form

**Comment by psparwez** [comment]
> The problem still exists; downgrading or updating packages does not fix it
> 
> The first issue report was published almost a year ago, and we still have no fix !?

For me, the issue was resolved by removing `node_modules` and `pnpm-lock.yaml` and then running `pnpm install` again. After that, everything worked with:

```json

{
  "@hookform/resolvers": "5.2.2",
  "react-hook-form": "^7.71.2",
  "zod": "4.3.6"
}

```

**Comment by joshu1024** [comment]
Downgrading  Zod to v3, worked for me ↓ 
pnpm remove zod
pnpm add zod@3

**Comment by thawancomt** [comment]
> updating all packages, remove `node_modules` and `pnpm-lock.yaml` fixed my issue

Worked here
thx

**Comment by hamzakargin** [comment]
> updating all packages, remove `node_modules` and `pnpm-lock.yaml` fixed my issue

Makes sense — lockfile reset fixed the resolver type mismatch.

**Comment by safi-siddiqui-github** [comment]
Updated: July 5, 2026

1. In a Next JS app, React Hook Form, Zod app, first try to remove [ .next , node_modules ]
`rm -rf .next node_modules`

2. Second, Before installing / updating packages close your editor, then update / install
`pnpm install`
OR
`npm install`

3. This typescript error goes away, if still issues occur, then use below fallback

Updates: 20 May, 2026
Solved In Next.js Zod React Hook Form App 
This function is basically a typed wrapper around zodResolver that forces React Hook Form to accept Zod schemas despite version/type mismatch.
Take anything that might be a Zod schema, force TypeScript to accept it as a valid resolver schema, then force the result to behave like a React Hook Form resolver for my form type.
Kindly note this is temporary fix until RHF team upgrades from zod v3 to zod v4

```
export const asZodResolver = <T extends FieldValues>(
  schema: unknown,
): Resolver<T> => {
  return zodResolver(
    schema as Parameters<typeof zodResolver>[0],
  ) as Resolver<T>;
};

const form = useForm<BlogPostCreateNewSchemaType>({
    resolver: asZodResolver<BlogPostCreateNewSchemaType>(
      BlogPostCreateNewSchema,
    ),
    defaultValues: {
      title: "",
    },
  });
```

**Comment by CarlosEGuerraSilva** [comment]
> > The problem still exists; downgrading or updating packages does not fix it
> > The first issue report was published almost a year ago, and we still have no fix !?
> 
> You might want to consider Tanstack Form

I ended up doing this

**Comment by dignat** [comment]
The issue still exists.

**Comment by HereOrCode** [comment]
The issue still exists.

**Comment by gauthieramano** [comment]
> > > The problem still exists; downgrading or updating packages does not fix it
> > > The first issue report was published almost a year ago, and we still have no fix !?
> > 
> > 
> > You might want to consider Tanstack Form
> 
> I ended up doing this

I've been enjoying using `React Hook From` for years, but today I also ended up using `TanStack Form` due to the lack of `Zod v4` support. And I must say I really like the `TanStack Form` philosophy. Just using the `TanStack Devtools` in conjunction with `TanStack Form` is worth the move.

### Note:

I have a `Next.js` application, but I didn't want to use the workaround exposed by @safi-siddiqui-github 

Hope this type error will be fixed, though.
